name: connectsphere
description: "ConnectSphere - Professional Dating & Social App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  card_swiper: ^3.0.1
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  http: ^1.2.2
  geolocator: ^14.0.2 # Updated
  geocoding: ^3.0.0
  flutter_local_notifications: ^19.3.0 # Updated
  socket_io_client: ^3.1.2 # Updated
  image_picker: ^1.1.2
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  flutter_staggered_animations: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0 # Updated

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/